### ISSUE TITLE
Feature: Adding multiculture (ENG/ESP) to mobile app

### ISSUE THREAD

**Issue by rcervantes** [rcervantes/cognitive-locator#72]

**Comment by dasanagu** [comment]
Lo harás con el plugin de @crossgeeks? https://xamgirl.com/multilingual-localization-plugin-for-xamarin

**Comment by rcervantes** [comment]
@dasanagu justamente estoy revisando, la verdad la implementación se ve sencilla en esta publicación: https://nnhiu.blogspot.mx/2014/07/resx-xamarin-forms.html

**Comment by rcervantes** [comment]
Completed!
